name: Build APK Debug
on: { workflow_dispatch: {} }

jobs:
  android-debug:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with: { node-version: 20 }
      - uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: 17
      - run: npm ci
      - name: Prebuild Android
        run: npx expo prebuild --platform android --non-interactive
      - name: Build debug APK
        run: |
          cd android
          ./gradlew assembleDebug
      - uses: actions/upload-artifact@v4
        with:
          name: ambi-vision-debug-apk
          path: android/app/build/outputs/apk/debug/app-debug.apk
